fix: improved deployment script

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -1,4 +1,3 @@
-
 name: Integration Workflow
 
 on:
@@ -19,54 +18,78 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Set up Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-          cache: 'yarn'
+
+      - name: Cache Yarn Dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.yarn/cache
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
 
       - name: Install Packages
         run: yarn install
 
-      - name: Check for linting issues
+      - name: Check for Linting Issues
         run: yarn run lint
 
-      - name: Build dist
+      - name: Build Project
         run: yarn run dev:build
 
   deploy:
     runs-on: ubuntu-latest
     needs: [build]
+
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
+
       - name: Install Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '16'
+
       - name: Set up SSH Connection
         uses: appleboy/ssh-action@master
         with:
-          host: ${{secrets.SERVER_IP}}
-          username: ${{secrets.USERNAME}}
-          passphrase: ${{secrets.PASSWORD}}
-          key: ${{secrets.SERVER_SSH_KEY}}
-          port: ${{secrets.PORT}}
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          port: ${{ secrets.PORT }}
           script: |
             set -e
             echo "Changing directory to /www/wwwroot/APIs/euapi"
-            cd /www/wwwroot/APIS/euapi || {echo "Failed to change directory"; exit 1;}
-            echo "Pulling Latest code from origin/main"
-            git pull origin main || { echo "Failed to pull latest code"; exit 1; }
+            if ! cd /www/wwwroot/APIs/euapi; then
+              echo "Failed to change directory"
+              exit 1
+            fi
+            echo "Pulling latest code from origin/main"
+            if ! git pull origin main; then
+              echo "Failed to pull latest code"
+              exit 1
+            fi
             echo "Installing dependencies"
-            yarn install || {echo "Failed to install dependencies"; exit 1;}
-            echo "Stopping Server To rebuilt"
-            yarn run docker:stop || {echo "Couldn't Stop Docker containers"; exit 1;}
-            echo "Building Development Files"
-            yarn run docker:build || {echo "Failed to build development server"; exit 1;}
+            if ! yarn install; then
+              echo "Failed to install dependencies"
+              exit 1
+            fi
+            echo "Stopping server to rebuild"
+            if ! yarn run docker:stop; then
+              echo "Couldn't stop Docker containers"
+              exit 1
+            fi
+            echo "Building development files"
+            if ! yarn run docker:build; then
+              echo "Failed to build development server"
+              exit 1
+            fi
             echo "Running deployment"
-            yarn run docker:run || {echo "Failed to start server"; exit 1;}
+            if ! yarn run docker:run; then
+              echo "Failed to start server"
+              exit 1
+            fi
             echo "Deployment successful"
-
-
-          
